[package]
name = "doom-crafter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "^1.0"
bevy = "0.16"
bevy_image_export = "0.13.0"
clap = { version = "4.5.1", features = ["derive"] }
image = "^0.24"
putpng = { git = "https://github.com/wojo81/putpng" }
tinywad = "*"
wild = "2.2.1"